# Problem 1

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0,10, size=5)
print("Matris:", matris)
# 3 - matris'in boyutunu öğrenin
print("Boyut", matris.shape)
# 4 - matris'i yeniden boyutlandırın
matris_reshaped = matris.reshape((5, 1))
print("Yeniden boyutlandirilmiş matris:\n", matris_reshaped)
# 5 - matris'in boyut sayısını öğrenin
print("Boyut sayisi", matris_reshaped.ndim)

Matris: [6 5 1 6 9]
Boyut (5,)
Yeniden boyutlandirilmiş matris:
 [[6]
 [5]
 [1]
 [6]
 [9]]
Boyut sayisi 2


# Problem 2

In [11]:
import numpy as np

# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
tek_sayilar = np.arange(1, 10, 2)  
matris = tek_sayilar.reshape(1, -1)  
print("Orijinal Matris:\n", matris)

# 2 - Oluşturduğunuz matrisi parçalayın (örneğin 2 parçaya bölelim)
parcalar = np.array_split(matris, 2, axis=1)  
print("\nParçalanmış Matrisler:")
for i, parca in enumerate(parcalar):
    print(f"Parça {i+1}:\n", parca)

# 3 - Parçalanmış matrisleri birleştirin
birlesmis_matris = np.hstack(parcalar)  
print("\nBirleştirilmiş Matris:\n", birlesmis_matris)


Orijinal Matris:
 [[1 3 5 7 9]]

Parçalanmış Matrisler:
Parça 1:
 [[1 3 5]]
Parça 2:
 [[7 9]]

Birleştirilmiş Matris:
 [[1 3 5 7 9]]


# Problem 3

In [12]:
import numpy as np

# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
sayilar = np.arange(5, 101, 2)
rastgele_sayilar = np.random.choice(sayilar, 10, replace=False)  
matris = rastgele_sayilar.reshape(2, 5)  
print("Oluşturulan Matris:\n", matris)

# 2 - Matris'in özelliklerini inceleyin
print("\nMatris Özellikleri:")
print(f"Şekli: {matris.shape}")  
print(f"Boyutu: {matris.size}")  
print(f"Veri Tipi: {matris.dtype}")  
print(f"Min Değer: {matris.min()}")  
print(f"Max Değer: {matris.max()}")  
print(f"Ortalama: {matris.mean()}")  
print(f"Standart Sapma: {matris.std()}")  


Oluşturulan Matris:
 [[35 43 13 65 63]
 [75 67 27 85 71]]

Matris Özellikleri:
Şekli: (2, 5)
Boyutu: 10
Veri Tipi: int64
Min Değer: 13
Max Değer: 85
Ortalama: 54.4
Standart Sapma: 22.253988406575573
